#!/usr/bin/env python3
"""
One-time cleanup: rounds every route's low/high rate to a whole number
across every cargo on the board. Mostly affects the routes generated by
add_tonnage_brackets.py (the +/-6%-per-bracket formula naturally produces
decimals like 103.9, 92.4, etc.) — real fixture-based rates were already
whole numbers, so this is a no-op for those.

Safe to re-run: rounding an already-whole number changes nothing.

Usage:
    python3 round_rates.py
It will prompt for your dashboard username and password (input hidden).
"""
import getpass
import json
import urllib.error
import urllib.request

API_BASE = "https://94-136-184-214.sslip.io"


def api_call(method, path, token=None, body=None):
    url = API_BASE + path
    data = json.dumps(body).encode("utf-8") if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Content-Type", "application/json")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        print("ERROR", e.code, e.read().decode("utf-8"))
        raise


def main():
    username = input("Dashboard username: ")
    password = getpass.getpass("Dashboard password: ")

    login = api_call("POST", "/api/login", body={"username": username, "password": password})
    token = login["token"]
    print("Logged in as", login["username"])

    state_resp = api_call("GET", "/api/state", token=token)
    state = state_resp.get("value") or {}
    cargo_data = state.get("board", {}).get("cargoData", {})

    changed = 0
    for cid, cargo in cargo_data.items():
        for route in cargo.get("routes", []):
            new_low = round(route["low"])
            new_high = round(route["high"])
            if new_low != route["low"] or new_high != route["high"]:
                route["low"] = new_low
                route["high"] = new_high
                changed += 1

    if not changed:
        print("Nothing to round \u2014 all rates already whole numbers.")
        return

    api_call("PUT", "/api/state", token=token, body={"value": state})
    print(f"Done. Rounded {changed} route(s) to whole-number rates.")


if __name__ == "__main__":
    main()
